# Generated by Django 5.1.5 on 2025-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_portal", "0004_servicerequest_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="file_attachment",
            field=models.ImageField(blank=True, null=True, upload_to="complaints/"),
        ),
    ]
