# Generated by Django 5.1.5 on 2025-01-18 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_portal", "0005_alter_servicerequest_file_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Billing", "Billing Issues"),
                    ("Outage", "Service Outage"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_service_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
