# Generated by Django 5.1.5 on 2025-01-18 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_portal", "0006_alter_servicerequest_request_type_and_more"),
        ("customer_support", "0002_servicerequest_supportcomment_delete_supportnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportcomment",
            name="request",
        ),
        migrations.AddField(
            model_name="supportcomment",
            name="service_request",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="customer_portal.servicerequest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supportcomment",
            name="support_rep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ServiceRequest",
        ),
    ]
